---
- name: Configure a Manjaro OS (Arch Linux distribution) desktop
  hosts: all
  roles:
    - {role: base, tags: [base]}
    - {role: development, tags: [development]}
    - {role: multimedia, tags: [multimedia]}
    - {role: security, tags: [security]}

  handlers:
    - name: Configure OS handler
      ansible.builtin.import_tasks: handlers/os.yml

    - name: Configure Freshclam OS
      ansible.builtin.import_tasks: handlers/freshclam.yml

    - name: Configure .zshrc
      ansible.builtin.import_tasks: handlers/zsh.yml
