- name: Docker - Install docker
  community.general.pacman:
    name: docker
    state: latest
  become: true
  tags:
    - development
    - docker

- name: Docker - Create daemon.json
  ansible.builtin.copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: "0644"
  become: true
  tags:
    - development
    - docker