- name: Docker - Install docker
  community.general.pacman:
    name: docker
    state: latest
  become: true
  tags:
    - development
    - docker

- name: Docker - Create config directory
  become: true
  file:
    path: /etc/docker
    state: directory
  tags:
    - docker
    - development

- name: Docker - Create daemon.json
  ansible.builtin.template:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: "0644"
  become: true
  tags:
    - development
    - docker

- name: Docker - Enable & Start the daemon
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: true