---
- name: Install browsers
  community.general.pacman:
    name: "{{ browsers }}"
    state: present
  become: true
  tags:
    - browsers

- name: Install browsers from Arch User Repository
  ansible.builtin.shell: |
    set -o pipefail
    pamac build -d --no-confirm {{ item }} | grep "is up to date"
    if [ $? != 0 ]; then
      pamac build --no-confirm {{ item }}
    fi
  with_items: "{{ browsers_aur }}"
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'successfully' in command_result.stdout"
  become: true
  tags:
    - browsers
    - aur