- name: Set the hostname
  become: true
  hostname:
    name: "{{ inventory_hostname }}"
  tags:
    - base
    - hostname

- name: set hostname in /etc/hosts
  become: true
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ inventory_hostname }}'
    state: present
  tags:
    - base
    - hostname