---
- name: Install oh-my-zsh-git
  ansible.builtin.shell: |
    set -o pipefail
    pamac build -d --no-confirm oh-my-zsh-git | grep -E 'is up to date|downgrading'
    if [ $? != 0 ]; then
      pamac build --no-confirm oh-my-zsh-git
    fi
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: "'successfully' in command_result.stdout"
  become: true
  tags:
    - zsh
    - aur

- name: Check if .zshrc exists on user home folder
  ansible.builtin.stat:
    path: /home/{{ user_name }}/.zshrc
  register: zsh_file_check
  tags:
    - zsh

- name: Copy .zshrc to home folder
  ansible.builtin.copy:
    remote_src: true
    src: /usr/share/oh-my-zsh/zshrc
    dest: /home/{{ user_name }}/.zshrc
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0644"
  become: true
  become_user: "{{ user_name }}"
  when: not zsh_file_check.stat.exists
  tags:
    - zsh

- name: Create zsh shell aliases
  ansible.builtin.lineinfile:
    dest: /home/{{ user_name }}/.zshrc
    regexp: '{{ item }}'
    insertafter: 'EOF'
    line: '{{ item }}'
    owner: '{{ user_name }}'
    state: present
  with_items: "{{ shell_aliases }}"
  become_user: "{{ user_name }}"
  become: true
  tags:
    - zsh

- name: Add zsh plugins
  ansible.builtin.replace:
    path: /home/{{ user_name }}/.zshrc
    regexp: plugins=(git)
    replace: plugins=(git git-extras git-prompt spring dotenv docker-compose docker colored-man-pages archlinux)
    backup: true
  become_user: "{{ user_name }}"
  become: true
  tags:
    - zsh

- name: Change zsh shell theme from 'robbyrussell' to 'agnoster'
  ansible.builtin.replace:
    path: /home/{{ user_name }}/.zshrc
    regexp: ZSH_THEME="robbyrussell"
    replace: ZSH_THEME="{{ zsh_theme | default("agnoster") }}"
    backup: true
  become_user: "{{ user_name }}"
  become: true
  tags:
    - zsh

- name: Set zsh as default shell
  ansible.builtin.user:
    name: "{{ user_name }}"
    shell: /usr/bin/zsh
  become: true
  tags:
    - zsh